"""add content_briefs brief_slides

Revision ID: 525cbfd0619e
Revises: 0619a5af74e9
Create Date: 2026-07-23 22:58:09.369479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '525cbfd0619e'
down_revision: Union[str, None] = '0619a5af74e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_briefs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.Enum('feed', 'story', 'carousel', name='content_type_brief'), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'tiktok', 'facebook', 'twitter', 'linkedin', name='platform_type'), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'generated', 'in_review', 'approved', 'published', name='brief_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brief_slides',
    sa.Column('brief_id', sa.UUID(), nullable=False),
    sa.Column('slide_title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['content_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('content_items')
    op.drop_table('campaigns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('campaigns_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('campaigns_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('campaigns_pkey'))
    )
    op.create_table('content_items',
    sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_type', postgresql.ENUM('feed', 'story', 'carousel', name='content_type'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'in_progress', 'generated', 'in_review', 'approved', 'published', name='content_status'), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('content_items_campaign_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('content_items_pkey'))
    )
    op.drop_table('brief_slides')
    op.drop_table('content_briefs')
    # ### end Alembic commands ###
