"""add slide_id to generated_designs

Revision ID: 70dea5f94a5b
Revises: 712d2957068d
Create Date: 2026-07-24 22:21:09.102822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dea5f94a5b'
down_revision: Union[str, None] = '712d2957068d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_designs', sa.Column('slide_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'generated_designs', 'brief_slides', ['slide_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_designs', type_='foreignkey')
    op.drop_column('generated_designs', 'slide_id')
    # ### end Alembic commands ###
