"""add generated_designs and credits tables

Revision ID: 712d2957068d
Revises: e63fd2638fa7
Create Date: 2026-07-24 21:40:06.413636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712d2957068d'
down_revision: Union[str, None] = 'e63fd2638fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('freelancer', 'starter', 'pro', name='credit_plan'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('generated_designs',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('content_brief_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('feed', 'story', 'carousel', name='design_content_type'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_brief_id'], ['content_briefs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_designs')
    op.drop_table('credits')
    # ### end Alembic commands ###
