"""add clients and brand_assets tables

Revision ID: d017d58685a5
Revises: e1a2b3c4d5e6
Create Date: 2026-07-23 16:50:39.299606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd017d58685a5'
down_revision: Union[str, None] = 'e1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='client_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_assets',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('logo', 'guideline', 'reference', 'font', name='asset_type'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('font_name', sa.String(length=255), nullable=True),
    sa.Column('font_type', sa.Enum('primary', 'secondary', 'accent', name='font_type'), nullable=True),
    sa.Column('brand_colors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_style', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_assets')
    op.drop_table('clients')
    # ### end Alembic commands ###
